from models import db, FishSpecies

# ── 31 fish the ML model can classify ─────────────────────────────────────────
MODEL_FISH = [
    {
        'name': 'Bangus',
        'scientific_name': 'Chanos chanos',
        'family': 'Chanidae',
        'habitat': 'Coastal marine waters, estuaries, brackish lagoons, and freshwater ponds',
        'diet': 'Algae, detritus, zooplankton, and organic matter on muddy bottoms',
        'average_size': '60–100 cm',
        'max_size': '180 cm',
        'weight_range': '0.5–14 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Streamlined silvery body, forked tail, small toothless mouth, large eyes with adipose eyelid',
        'description': 'Bangus (Milkfish) is the national fish of the Philippines. It is widely farmed across Southeast Asia and is prized for its rich, milky flesh.',
        'fun_facts': 'Can survive in freshwater, brackish, and saltwater. Has over 500 small bones, making preparation an art form.',
        'native_regions': 'Indo-Pacific — Philippines, Indonesia, Taiwan, India',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Big Head Carp',
        'scientific_name': 'Hypophthalmichthys nobilis',
        'family': 'Cyprinidae',
        'habitat': 'Large rivers, lakes, and reservoirs with slow or still water',
        'diet': 'Zooplankton, phytoplankton, and organic detritus filtered from water',
        'average_size': '50–90 cm',
        'max_size': '146 cm',
        'weight_range': '2–40 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Very large head relative to body size, low-set eyes, large mouth, silvery-grey sides',
        'description': 'Native to China and eastern Siberia. One of the most important aquaculture species worldwide. Considered invasive in North America.',
        'fun_facts': 'Can filter up to 20 litres of water per minute. Has been cultured in China for over 2,000 years.',
        'native_regions': 'China, Russia (Amur River), widely introduced globally',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Black Spotted Barb',
        'scientific_name': 'Dawkinsia filamentosa',
        'family': 'Cyprinidae',
        'habitat': 'Fast-flowing hill streams and rivers with rocky substrates',
        'diet': 'Algae, small invertebrates, plant matter, and insects',
        'average_size': '10–15 cm',
        'max_size': '20 cm',
        'weight_range': '50–200 g',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Silvery body with prominent black spot near the tail, orange-red fins in males, elongated dorsal fin ray',
        'description': 'A popular aquarium fish native to South India and Sri Lanka. Males develop an elongated filamentous dorsal fin ray during breeding season.',
        'fun_facts': 'Males display brilliant orange coloration during spawning. Often kept in large aquarium schools.',
        'native_regions': 'South India, Sri Lanka',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Catfish',
        'scientific_name': 'Silurus glanis / various species',
        'family': 'Siluridae / Ictaluridae',
        'habitat': 'Rivers, lakes, ponds, swamps, and slow-moving muddy waters',
        'diet': 'Fish, frogs, crustaceans, insects, worms, and organic debris',
        'average_size': '30–80 cm',
        'max_size': '300 cm (Wels Catfish)',
        'weight_range': '0.5–100+ kg',
        'danger_level': 'Mildly Dangerous (spines can puncture skin)',
        'edible': 'Yes',
        'conservation_status': 'Varies by species',
        'characteristics': 'Scaleless body, prominent whisker-like barbels around mouth, flattened head, dorsal and pectoral fin spines',
        'description': 'Catfish are a diverse group of ray-finned fish found on every continent except Antarctica. Many species are commercially farmed.',
        'fun_facts': 'Some species can walk on land using their pectoral fins. The Wels Catfish is one of the largest freshwater fish in Europe.',
        'native_regions': 'Worldwide — Americas, Africa, Asia, Europe',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Climbing Perch',
        'scientific_name': 'Anabas testudineus',
        'family': 'Anabantidae',
        'habitat': 'Stagnant ponds, rice paddies, swamps, and slow-moving streams',
        'diet': 'Insects, worms, crustaceans, small fish, and plant matter',
        'average_size': '15–20 cm',
        'max_size': '25 cm',
        'weight_range': '100–400 g',
        'danger_level': 'Mildly Dangerous (sharp gill covers can scratch)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Oval body with rough ctenoid scales, spiny gill covers, labyrinth organ for breathing air',
        'description': 'Famous for its ability to breathe air and travel across land between water bodies using its spiny gill covers and fins.',
        'fun_facts': 'Can survive out of water for several hours. Can "climb" short distances overland to find new water sources.',
        'native_regions': 'South and Southeast Asia — India, Philippines, Thailand, Indonesia',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Fourfinger Threadfin',
        'scientific_name': 'Eleutheronema tetradactylum',
        'family': 'Polynemidae',
        'habitat': 'Estuaries, coastal shallows, and turbid inshore waters',
        'diet': 'Crustaceans, small fish, and invertebrates',
        'average_size': '30–60 cm',
        'max_size': '200 cm',
        'weight_range': '0.5–15 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Four long free pectoral fin rays (thread-like), blunt snout, inferior mouth, silvery body',
        'description': 'A highly prized food fish in Southeast Asia and Australia. The four distinctive free pectoral rays are used to feel for prey in murky water.',
        'fun_facts': 'The long thread-like fin rays act as tactile organs to detect prey in low visibility. Highly valued in Chinese cuisine.',
        'native_regions': 'Indo-Pacific — Australia, India, Southeast Asia',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Freshwater Eel',
        'scientific_name': 'Anguilla spp.',
        'family': 'Anguillidae',
        'habitat': 'Rivers, streams, estuaries, and lakes; migrates to sea to spawn',
        'diet': 'Fish, frogs, crustaceans, worms, and insects',
        'average_size': '40–100 cm',
        'max_size': '200 cm',
        'weight_range': '0.2–7 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Endangered (A. anguilla), Vulnerable (A. rostrata)',
        'characteristics': 'Long snake-like body, smooth scaleless skin with thick mucus, small pectoral fins, continuous dorsal-caudal-anal fin',
        'description': 'Catadromous fish that live in freshwater but migrate thousands of kilometres to the ocean to spawn. Highly valued in Japanese cuisine (unagi).',
        'fun_facts': 'European eels travel over 6,000 km to the Sargasso Sea to spawn. Their entire life cycle was only recently mapped.',
        'native_regions': 'Europe, North America, Asia, Australia',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Glass Perchlet',
        'scientific_name': 'Parambassis ranga',
        'family': 'Ambassidae',
        'habitat': 'Slow-moving freshwater rivers, ponds, lakes, and flooded fields',
        'diet': 'Small insects, zooplankton, and tiny invertebrates',
        'average_size': '4–6 cm',
        'max_size': '8 cm',
        'weight_range': '2–10 g',
        'danger_level': 'Safe',
        'edible': 'Rarely (too small)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Completely transparent body revealing internal organs, compressed oval shape, forked tail',
        'description': 'One of the most remarkable freshwater fish for its near-complete transparency. Popular in the aquarium trade.',
        'fun_facts': 'Its transparent body allows you to see its beating heart, spine, and internal organs. Sometimes dyed artificially for pet trade (unethical practice).',
        'native_regions': 'South and Southeast Asia — India, Bangladesh, Myanmar',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Goby',
        'scientific_name': 'Gobiidae family',
        'family': 'Gobiidae',
        'habitat': 'Coral reefs, rocky shores, estuaries, mudflats, and freshwater streams',
        'diet': 'Algae, small invertebrates, detritus, and plankton',
        'average_size': '5–15 cm',
        'max_size': '30 cm',
        'weight_range': '10–200 g',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Varies by species',
        'characteristics': 'Fused pelvic fins forming a suction cup, elongated cylindrical body, large eyes placed high on head',
        'description': 'Gobies are one of the largest fish families with over 2,000 species. Many can cling to rocks using their fused pelvic fins.',
        'fun_facts': 'Some gobies are cleaner fish, removing parasites from larger fish. The dwarf pygmy goby is one of the smallest vertebrates on Earth.',
        'native_regions': 'Worldwide in tropical and temperate waters',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Gold Fish',
        'scientific_name': 'Carassius auratus',
        'family': 'Cyprinidae',
        'habitat': 'Ponds, slow rivers, and aquariums',
        'diet': 'Algae, plant matter, insects, crustaceans, and prepared pellets',
        'average_size': '15–30 cm',
        'max_size': '59 cm',
        'weight_range': '0.1–4 kg',
        'danger_level': 'Safe',
        'edible': 'Caution (not typically eaten; may carry parasites)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Stocky body, metallic gold or orange coloration, no barbels, large scales, forked tail',
        'description': 'One of the earliest fish to be domesticated. Originating from China over 1,000 years ago, goldfish now exist in hundreds of bred varieties.',
        'fun_facts': 'Can live over 25 years. Wild goldfish are actually olive-green. They can recognize their owners and be trained to perform tricks.',
        'native_regions': 'Originally China; now worldwide in captivity',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Gourami',
        'scientific_name': 'Osphronemus goramy',
        'family': 'Osphronemidae',
        'habitat': 'Swamps, marshes, lakes, and slow rivers with dense vegetation',
        'diet': 'Plant material, algae, insects, worms, and small fish',
        'average_size': '20–45 cm',
        'max_size': '70 cm',
        'weight_range': '0.5–9 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Laterally compressed body, long ventral fin filaments, labyrinth organ for air breathing, vibrant colors',
        'description': 'The Giant Gourami is a major food fish in Southeast Asia. Smaller species like the Dwarf Gourami are popular aquarium fish.',
        'fun_facts': 'Builds bubble nests for spawning. Has a labyrinth organ allowing it to breathe atmospheric air. Some species can live 20+ years.',
        'native_regions': 'Southeast Asia — Indonesia, Malaysia, Thailand',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Grass Carp',
        'scientific_name': 'Ctenopharyngodon idella',
        'family': 'Cyprinidae',
        'habitat': 'Large rivers, lakes, and canals with abundant aquatic vegetation',
        'diet': 'Exclusively aquatic and terrestrial plants; a true herbivore',
        'average_size': '60–100 cm',
        'max_size': '150 cm',
        'weight_range': '2–45 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Torpedo-shaped body, large scales with dark edges, blunt rounded head, no barbels',
        'description': 'The most produced fish in aquaculture globally. Introduced worldwide to control aquatic vegetation, sometimes with negative ecological effects.',
        'fun_facts': 'Can consume 40% of its body weight in plants daily. Sterile triploid versions are used for weed control to prevent invasive reproduction.',
        'native_regions': 'China, Eastern Russia (Amur River)',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Green Spotted Puffer',
        'scientific_name': 'Tetraodon nigroviridis',
        'family': 'Tetraodontidae',
        'habitat': 'Estuaries, mangroves, tidal creeks, and brackish coastal waters',
        'diet': 'Snails, clams, crustaceans, and invertebrates with hard shells',
        'average_size': '10–15 cm',
        'max_size': '17 cm',
        'weight_range': '20–100 g',
        'danger_level': 'Dangerous (Tetrodotoxin — highly toxic)',
        'edible': 'No — TOXIC',
        'conservation_status': 'Least Concern',
        'characteristics': 'Round inflatable body, bright green top with black spots, white underside, beak-like fused teeth, no scales',
        'description': 'Contains tetrodotoxin (TTX), one of the most potent neurotoxins. Do NOT consume. Popular aquarium fish but requires brackish water.',
        'fun_facts': 'Can inflate its body to 3x its normal size. Its beak-like teeth never stop growing. There is no antidote to tetrodotoxin.',
        'native_regions': 'Southeast Asia — Thailand, Indonesia, Philippines',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Indian Carp',
        'scientific_name': 'Labeo rohita',
        'family': 'Cyprinidae',
        'habitat': 'Large warm rivers and lakes with silty or muddy substrates',
        'diet': 'Algae, plant detritus, zooplankton, and organic matter from substrate',
        'average_size': '40–90 cm',
        'max_size': '200 cm',
        'weight_range': '1–45 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Vulnerable',
        'characteristics': 'Deep body with reddish tinge on fins, fringed lips for scraping algae, cycloid scales',
        'description': 'Rohu is one of the most important freshwater food fish in South Asia. It is the most cultured fish in India and Bangladesh.',
        'fun_facts': 'Can live up to 10 years. Rohu is a symbol of good luck in Bengali culture and is served at almost every celebration.',
        'native_regions': 'India, Nepal, Bangladesh, Pakistan, Myanmar',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Indo-Pacific Tarpon',
        'scientific_name': 'Megalops cyprinoides',
        'family': 'Megalopidae',
        'habitat': 'Estuaries, mangroves, rivers, and coastal shallow seas',
        'diet': 'Fish, crustaceans, and insects near the water surface',
        'average_size': '30–60 cm',
        'max_size': '150 cm',
        'weight_range': '0.5–18 kg',
        'danger_level': 'Safe',
        'edible': 'Yes (bony)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Large silver scales, upturned mouth, elongated dorsal fin ray, large eyes, compressed body',
        'description': 'A prized sport fish known for spectacular aerial jumps when hooked. Related to the Atlantic Tarpon but smaller.',
        'fun_facts': 'Can breathe air using a modified swim bladder, allowing survival in low-oxygen waters. Considered a top game fish.',
        'native_regions': 'Indo-Pacific — East Africa to Australia and Polynesia',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Jaguar Gapote',
        'scientific_name': 'Parachromis managuensis',
        'family': 'Cichlidae',
        'habitat': 'Lakes, ponds, and rivers with murky water and muddy or sandy bottoms',
        'diet': 'Fish, crustaceans, insects, and any prey it can fit in its mouth',
        'average_size': '35–55 cm',
        'max_size': '63 cm',
        'weight_range': '1–5 kg',
        'danger_level': 'Mildly Dangerous (aggressive, sharp teeth)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Gold/cream body with irregular black blotches resembling a jaguar pattern, large protruding jaw',
        'description': 'Native to Central America and now invasive in many regions. Aggressive predator valued both as food and in the aquarium trade.',
        'fun_facts': 'One of the most aggressive cichlids. In the wild, it lurks motionless before ambushing prey at lightning speed.',
        'native_regions': 'Central America — Nicaragua, Honduras, Guatemala; introduced worldwide',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Janitor Fish',
        'scientific_name': 'Pterygoplichthys spp.',
        'family': 'Loricariidae',
        'habitat': 'Slow-moving rivers, lakes, and heavily vegetated waters',
        'diet': 'Algae, biofilm, wood, plant material, and organic detritus',
        'average_size': '30–50 cm',
        'max_size': '70 cm',
        'weight_range': '0.5–2 kg',
        'danger_level': 'Mildly Dangerous (sharp bony plates can cut)',
        'edible': 'Caution (bony, not widely eaten)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Armored with bony scutes, suckermouth, flat underside, large sail-like dorsal fin',
        'description': 'Called "Janitor Fish" because it eats algae and keeps tanks clean. Originally from South America, it is now invasive in many countries including the Philippines.',
        'fun_facts': 'Can breathe air using a specialized stomach. Invasive populations have damaged native fish populations in the Philippines by competing for food and clogging waterways.',
        'native_regions': 'South America; invasive in Southeast Asia and elsewhere',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Knifefish',
        'scientific_name': 'Chitala spp. / Notopterus spp.',
        'family': 'Notopteridae',
        'habitat': 'Slow rivers, lakes, flooded forests, and swamps',
        'diet': 'Small fish, crustaceans, insects, and organic matter',
        'average_size': '30–60 cm',
        'max_size': '122 cm',
        'weight_range': '0.5–7 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Near Threatened',
        'characteristics': 'Long knife-like body, long anal fin running most of body length, tiny dorsal fin or none, hump behind head on some species',
        'description': 'Named for their blade-like body shape. They swim by undulating their long anal fin. Popular food fish in Southeast Asia.',
        'fun_facts': 'Can swim forwards and backwards with equal ease. Uses a weak electric field for navigation in murky water.',
        'native_regions': 'Southeast Asia — Thailand, Indonesia, Philippines, India',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Long-Snouted Pipefish',
        'scientific_name': 'Doryichthys boaja',
        'family': 'Syngnathidae',
        'habitat': 'Freshwater rivers and estuaries with dense aquatic vegetation',
        'diet': 'Tiny crustaceans, zooplankton, and small invertebrates',
        'average_size': '15–25 cm',
        'max_size': '40 cm',
        'weight_range': '5–30 g',
        'danger_level': 'Safe',
        'edible': 'No (too small, bony, not used as food)',
        'conservation_status': 'Data Deficient',
        'characteristics': 'Very elongated pipe-like body covered in bony rings, long tubular snout, tiny fins',
        'description': 'A relative of seahorses. Males carry and incubate eggs in a brood pouch on the underside of their tail.',
        'fun_facts': 'Like seahorses, males are the ones that carry and give birth to young. They suck prey into their tube-like mouth in a rapid vacuum.',
        'native_regions': 'Southeast Asia — Borneo, Java, Sumatra, Philippines',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Mosquito Fish',
        'scientific_name': 'Gambusia affinis',
        'family': 'Poeciliidae',
        'habitat': 'Ponds, marshes, slow streams, ditches, and rice paddies',
        'diet': 'Mosquito larvae, zooplankton, algae, and small invertebrates',
        'average_size': '2.5–4 cm (female larger)',
        'max_size': '6 cm',
        'weight_range': '1–5 g',
        'danger_level': 'Safe',
        'edible': 'No (too small)',
        'conservation_status': 'Least Concern (invasive in many regions)',
        'characteristics': 'Small stout body, rounded tail, upturned mouth, live-bearing',
        'description': 'Introduced worldwide to control mosquito populations. Now considered one of the 100 worst invasive species due to harm to native fish.',
        'fun_facts': 'A female can give birth to 60 young every 4–6 weeks. Gives birth to live young, not eggs. Can eat 40–100% of its body weight in mosquito larvae daily.',
        'native_regions': 'Originally eastern USA; introduced worldwide',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Mudfish',
        'scientific_name': 'Channa striata',
        'family': 'Channidae',
        'habitat': 'Swamps, rice fields, canals, rivers, and muddy ponds',
        'diet': 'Fish, frogs, insects, worms, and crustaceans',
        'average_size': '30–50 cm',
        'max_size': '90 cm',
        'weight_range': '0.2–5 kg',
        'danger_level': 'Mildly Dangerous (sharp teeth)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Cylindrical body, large head resembling a snake, long dorsal fin, mottled brown-grey coloration',
        'description': 'Also called Snakehead Murrel. Can breathe air and survive in low-oxygen waters. Highly valued across Southeast Asia for its white, flavorful flesh.',
        'fun_facts': 'Can survive in mud during dry seasons (aestivation). Females are protective parents. Used in traditional medicine for wound healing.',
        'native_regions': 'South and Southeast Asia — India to China, Philippines',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Mullet',
        'scientific_name': 'Mugil cephalus',
        'family': 'Mugilidae',
        'habitat': 'Coastal waters, estuaries, lagoons, and lower freshwater rivers',
        'diet': 'Algae, detritus, sediment microorganisms, and organic matter',
        'average_size': '30–50 cm',
        'max_size': '120 cm',
        'weight_range': '0.3–8 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Cylindrical streamlined body, two separate dorsal fins, large scales, blunt rounded snout',
        'description': 'One of the most widely distributed fish. Its roe (botargo) is a prized delicacy in Mediterranean countries.',
        'fun_facts': 'Known for jumping out of water, especially when startled. Mullet roe has been salted and dried since ancient Egyptian times.',
        'native_regions': 'Worldwide in tropical and temperate coastal areas',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Pangasius',
        'scientific_name': 'Pangasianodon hypophthalmus',
        'family': 'Pangasiidae',
        'habitat': 'Large tropical rivers, floodplains, and reservoirs',
        'diet': 'Fish, crustaceans, plant matter, fruits, and organic debris',
        'average_size': '50–100 cm',
        'max_size': '130 cm',
        'weight_range': '1–44 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Endangered',
        'characteristics': 'No scales (naked skin), two pairs of barbels, deeply forked tail, dark grey back and white belly',
        'description': 'Also known as Basa or Swai. One of the most important aquaculture fish globally, farmed intensively in Vietnam along the Mekong River.',
        'fun_facts': 'Migrates up to 1,000 km in the wild to spawn. Vietnam exports over 1.5 million tonnes of pangasius per year.',
        'native_regions': 'Mekong and Chao Phraya basins — Vietnam, Thailand, Cambodia',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Perch',
        'scientific_name': 'Perca fluviatilis',
        'family': 'Percidae',
        'habitat': 'Lakes, rivers, ponds, and slow streams with vegetation',
        'diet': 'Small fish, insects, crustaceans, worms, and fry',
        'average_size': '20–40 cm',
        'max_size': '60 cm',
        'weight_range': '0.2–4.8 kg',
        'danger_level': 'Mildly Dangerous (sharp dorsal spines)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Greenish body with 5–9 dark vertical bars, orange-red pelvic and anal fins, two dorsal fins, spiny gill covers',
        'description': 'One of the most popular freshwater sport fish in Europe. The flesh is white, firm, and highly regarded by anglers.',
        'fun_facts': 'Perch are schooling fish that hunt cooperatively, herding prey fish. The world record perch weighed 4.75 kg.',
        'native_regions': 'Europe, Asia; introduced to Australia, Africa, North America',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Scat Fish',
        'scientific_name': 'Scatophagus argus',
        'family': 'Scatophagidae',
        'habitat': 'Estuaries, mangroves, harbors, and coastal freshwater rivers',
        'diet': 'Algae, plant matter, invertebrates, and organic waste',
        'average_size': '20–30 cm',
        'max_size': '38 cm',
        'weight_range': '0.2–1.5 kg',
        'danger_level': 'Mildly Dangerous (venomous dorsal spines)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Deep compressed body, silver or green with large round dark spots, venomous dorsal fin spines',
        'description': 'The name means "feces eater" — it is known to feed in sewage outflows. Popular in aquariums and as a food fish in Asia despite its scavenging habits.',
        'fun_facts': 'Venomous spines can cause painful wounds. Despite feeding on waste, the flesh is considered tasty when sourced from clean water.',
        'native_regions': 'Indo-Pacific — India to Australia and Polynesia',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Silver Barb',
        'scientific_name': 'Barbonymus gonionotus',
        'family': 'Cyprinidae',
        'habitat': 'Rivers, lakes, floodplains, and canals in lowland areas',
        'diet': 'Aquatic plants, algae, small invertebrates, and plankton',
        'average_size': '20–30 cm',
        'max_size': '40 cm',
        'weight_range': '0.2–2 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Deep, laterally compressed silver body, large scales, reddish tail fin, two pairs of barbels',
        'description': 'One of the most important aquaculture fish in Southeast Asia. Fast growing and tolerant of crowded conditions.',
        'fun_facts': 'Can grow to market size in just 6 months. Has been selectively bred to reduce number of intermuscular bones.',
        'native_regions': 'Southeast Asia — Thailand, Cambodia, Vietnam, Indonesia',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Silver Carp',
        'scientific_name': 'Hypophthalmichthys molitrix',
        'family': 'Cyprinidae',
        'habitat': 'Large rivers and lakes; prefers open water',
        'diet': 'Phytoplankton, algae, and fine detritus filtered from water',
        'average_size': '50–100 cm',
        'max_size': '140 cm',
        'weight_range': '2–50 kg',
        'danger_level': 'Mildly Dangerous (leaps from water when startled — can injure boaters)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Silver streamlined body, low-set eyes, upturned mouth, long keel-like belly ridge',
        'description': 'Massively important in Chinese aquaculture. Considered highly invasive in North America, where it leaps from water when startled by boat motors.',
        'fun_facts': 'Can jump up to 3 metres out of water. In the US, boaters wear helmets to protect from leaping silver carp. The most produced fish species globally.',
        'native_regions': 'China, Russia; introduced across 6 continents',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Silver Perch',
        'scientific_name': 'Bidyanus bidyanus',
        'family': 'Terapontidae',
        'habitat': 'Rivers, lakes, and reservoirs in warm temperate to subtropical regions',
        'diet': 'Algae, zooplankton, aquatic insects, and plant matter',
        'average_size': '20–35 cm',
        'max_size': '60 cm',
        'weight_range': '0.2–4 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Vulnerable',
        'characteristics': 'Deep compressed body, silvery-grey with dark scale edges, small head, inferior mouth',
        'description': 'Endemic to the Murray-Darling Basin in Australia. Once abundant, now declining due to habitat changes, weirs, and introduced species.',
        'fun_facts': 'Listed as Vulnerable in Australia. One of the most sought-after native sport fish. Thrives in warm turbid waters that other fish avoid.',
        'native_regions': 'Australia (Murray-Darling Basin)',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Snakehead',
        'scientific_name': 'Channa micropeltes',
        'family': 'Channidae',
        'habitat': 'Swamps, lakes, rivers, rice paddies, and stagnant water bodies',
        'diet': 'Fish, frogs, small reptiles, birds, and mammals near water surface',
        'average_size': '50–100 cm',
        'max_size': '130 cm',
        'weight_range': '0.5–20 kg',
        'danger_level': 'Dangerous (aggressive, sharp teeth, will bite humans)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Long cylindrical body, flattened head, large mouth with sharp teeth, mottled brown-green pattern',
        'description': 'The Giant Snakehead is a voracious apex predator. It can breathe air, crawl overland, and survive for days out of water. Highly invasive globally.',
        'fun_facts': 'Will aggressively defend its nest and has been known to attack humans. Can travel over land to new water bodies. Considered a "Frankenfish" in North America.',
        'native_regions': 'Southeast Asia — Malaysia, Indonesia, Thailand; invasive in USA and Europe',
        'water_type': 'Freshwater',
        'in_model': True,
    },
    {
        'name': 'Tenpounder',
        'scientific_name': 'Elops saurus',
        'family': 'Elopidae',
        'habitat': 'Shallow coastal waters, estuaries, lagoons, and mangrove areas',
        'diet': 'Small fish, shrimp, and crustaceans near the water surface',
        'average_size': '40–70 cm',
        'max_size': '100 cm',
        'weight_range': '0.5–7 kg',
        'danger_level': 'Safe',
        'edible': 'Caution (very bony)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Slender silvery body, large scales, deeply forked tail, single dorsal fin, terminal mouth',
        'description': 'A coastal game fish known for spectacular leaps. Related to the tarpon. Edible but very bony so not highly prized as food.',
        'fun_facts': 'A primitive fish whose anatomy has changed little in millions of years. Goes through a transparent leptocephalus larval stage similar to eels.',
        'native_regions': 'Tropical Atlantic and Indo-Pacific coasts',
        'water_type': 'Brackish',
        'in_model': True,
    },
    {
        'name': 'Tilapia',
        'scientific_name': 'Oreochromis niloticus',
        'family': 'Cichlidae',
        'habitat': 'Ponds, rivers, lakes, and irrigation canals in warm climates',
        'diet': 'Algae, phytoplankton, aquatic plants, and organic detritus',
        'average_size': '25–45 cm',
        'max_size': '60 cm',
        'weight_range': '0.5–5 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Deep laterally compressed body, dark lateral stripes on tail, long continuous dorsal fin, subtle pink flush when mature',
        'description': 'One of the most farmed fish globally and the 4th most consumed in the USA. Adaptable, fast-growing, and cheap to produce.',
        'fun_facts': 'Mouthbrooders — females carry fertilized eggs and fry in their mouths. Called "aquatic chicken" due to its mild flavour and easy farming. Tolerates brackish water.',
        'native_regions': 'Africa (Nile River); now farmed on every continent',
        'water_type': 'Freshwater',
        'in_model': True,
    },
]

# ── Additional fish from online sources (not in ML model) ─────────────────────
EXTRA_FISH = [
    {
        'name': 'Atlantic Salmon',
        'scientific_name': 'Salmo salar',
        'family': 'Salmonidae',
        'habitat': 'Cold freshwater rivers and streams; open ocean (anadromous)',
        'diet': 'Insects, crustaceans, small fish, and squid',
        'average_size': '60–100 cm',
        'max_size': '150 cm',
        'weight_range': '2–46 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern (wild populations declining)',
        'characteristics': 'Silvery body, black spots above lateral line, red spots during spawning, adipose fin',
        'description': 'One of the most commercially important fish in the world. Anadromous — born in freshwater, migrates to sea, returns to birthplace to spawn.',
        'fun_facts': 'Returns to the exact river where it was born to spawn, using Earth\'s magnetic field. Can jump up to 3.6 m vertically.',
        'native_regions': 'North Atlantic Ocean, rivers of Europe and North America',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Rainbow Trout',
        'scientific_name': 'Oncorhynchus mykiss',
        'family': 'Salmonidae',
        'habitat': 'Cold, clear, oxygen-rich rivers, streams, and lakes',
        'diet': 'Insects, earthworms, crustaceans, and small fish',
        'average_size': '30–76 cm',
        'max_size': '120 cm',
        'weight_range': '0.5–25 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Brilliant pink-red lateral stripe, black spots on body and fins, silver-olive coloration',
        'description': 'One of the most widely farmed and sport-fished species globally. Native to the Pacific drainages of North America and Asia.',
        'fun_facts': 'Requires water temperatures below 20°C. Hatchery-raised fish can weigh over 20 kg. The sea-run form is called Steelhead.',
        'native_regions': 'Western North America, Pacific drainages of Asia; introduced worldwide',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Common Carp',
        'scientific_name': 'Cyprinus carpio',
        'family': 'Cyprinidae',
        'habitat': 'Slow rivers, ponds, lakes, and reservoirs — tolerates poor water quality',
        'diet': 'Invertebrates, plant material, algae, and organic detritus',
        'average_size': '40–80 cm',
        'max_size': '120 cm',
        'weight_range': '1–40 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Vulnerable (wild populations)',
        'characteristics': 'Olive-bronze body, large scales, two pairs of barbels, arched back, strong dorsal spine',
        'description': 'One of the oldest farmed fish, cultured for over 2,000 years. Extremely adaptable and considered invasive in Australia and North America.',
        'fun_facts': 'Can live over 50 years. Koi fish are domesticated varieties of common carp. Considered a pest in Australia where it degrades waterways.',
        'native_regions': 'Originally Danube River basin, Asia; now worldwide',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Clownfish',
        'scientific_name': 'Amphiprioninae',
        'family': 'Pomacentridae',
        'habitat': 'Coral reefs in warm shallow tropical waters; always near anemones',
        'diet': 'Algae, plankton, small invertebrates, and anemone leftovers',
        'average_size': '8–15 cm',
        'max_size': '18 cm',
        'weight_range': '20–100 g',
        'danger_level': 'Safe',
        'edible': 'No (protected, not eaten)',
        'conservation_status': 'Least Concern (some species threatened)',
        'characteristics': 'Bright orange with white bars outlined in black, stocky body',
        'description': 'Famous from "Finding Nemo." Lives in a symbiotic relationship with sea anemones, protected by their stinging tentacles.',
        'fun_facts': 'All clownfish are born male. The dominant fish in a group becomes female. They can live 6–10 years in the wild.',
        'native_regions': 'Indo-Pacific coral reefs — Red Sea to Australia',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Blue Marlin',
        'scientific_name': 'Makaira nigricans',
        'family': 'Istiophoridae',
        'habitat': 'Open ocean (pelagic), typically in warm tropical and subtropical waters',
        'diet': 'Tuna, mackerel, squid, and other large pelagic fish',
        'average_size': '200–400 cm',
        'max_size': '500 cm',
        'weight_range': '90–900 kg',
        'danger_level': 'Dangerous (bill can impale humans)',
        'edible': 'Yes (not preferred; strong flavour)',
        'conservation_status': 'Vulnerable',
        'characteristics': 'Cobalt blue back, silver belly, long pointed bill (rostrum), rigid sickle-shaped dorsal fin',
        'description': 'One of the most prized game fish. Females are significantly larger than males. Capable of swimming at 110 km/h in short bursts.',
        'fun_facts': 'Can swim at over 100 km/h. Uses its bill to stun prey, not spear it. The bill can grow to 1 metre long.',
        'native_regions': 'Atlantic and Pacific Oceans in tropical and subtropical zones',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Piranha',
        'scientific_name': 'Pygocentrus nattereri',
        'family': 'Serrasalmidae',
        'habitat': 'Rivers, lakes, and flooded forests of South America',
        'diet': 'Fish, insects, worms, crustaceans, seeds, and carrion',
        'average_size': '15–25 cm',
        'max_size': '50 cm',
        'weight_range': '0.5–3.5 kg',
        'danger_level': 'Dangerous (razor-sharp teeth, aggressive in groups)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Deep compressed body, powerful jaw, razor-sharp interlocking teeth, reddish belly',
        'description': 'Infamous for their sharp teeth and aggressive feeding frenzies. Despite their reputation, attacks on humans are rare and rarely fatal.',
        'fun_facts': 'Their teeth are replaceable throughout life. They can strip a large animal to bones in minutes as a group. Actually more scared of humans than the reverse.',
        'native_regions': 'Amazon and Orinoco river basins, South America',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Manta Ray',
        'scientific_name': 'Mobula birostris',
        'family': 'Mobulidae',
        'habitat': 'Open ocean and coastal tropical and subtropical waters',
        'diet': 'Zooplankton, fish eggs, and small fish filtered from water',
        'average_size': '400–700 cm wingspan',
        'max_size': '910 cm wingspan',
        'weight_range': '1,350–2,000 kg',
        'danger_level': 'Safe (no venomous spine)',
        'edible': 'No (protected by CITES)',
        'conservation_status': 'Endangered',
        'characteristics': 'Massive triangular pectoral fins, flat body, cephalic fins on head, no tail spine',
        'description': 'The largest rays in the world. Gentle filter feeders that breach dramatically out of water. Protected internationally but threatened by gill plate trade.',
        'fun_facts': 'Have the largest brain-to-body ratio of any fish. Can hold their breath (stop ventilating) for up to 24 minutes. May live to 40+ years.',
        'native_regions': 'Tropical and subtropical oceans worldwide',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Great White Shark',
        'scientific_name': 'Carcharodon carcharias',
        'family': 'Lamnidae',
        'habitat': 'Coastal and offshore temperate and subtropical seas',
        'diet': 'Seals, sea lions, dolphins, large fish, rays, and whale carcasses',
        'average_size': '350–500 cm',
        'max_size': '600 cm',
        'weight_range': '680–2,270 kg',
        'danger_level': 'Dangerous',
        'edible': 'No (CITES protected; fins are sometimes illegally traded)',
        'conservation_status': 'Vulnerable',
        'characteristics': 'White belly, grey back (countershading), torpedo body, rows of serrated triangular teeth, black eyes',
        'description': 'The largest predatory fish on Earth. Despite its fearsome reputation, it is responsible for relatively few human fatalities per year.',
        'fun_facts': 'Can detect one drop of blood in 100 litres of water. Has up to 300 teeth in several rows. Warm-blooded unlike most fish.',
        'native_regions': 'Temperate and subtropical coastal oceans worldwide',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Tuna',
        'scientific_name': 'Thunnus thynnus',
        'family': 'Scombridae',
        'habitat': 'Open ocean pelagic zone, both tropical and temperate waters',
        'diet': 'Mackerel, herring, squid, crustaceans, and other pelagic fish',
        'average_size': '150–200 cm',
        'max_size': '300 cm',
        'weight_range': '30–450 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Endangered (Atlantic Bluefin)',
        'characteristics': 'Metallic blue-black back, silver-white belly, crescent-shaped tail, bullet-shaped body',
        'description': 'Among the fastest fish in the ocean. Atlantic Bluefin Tuna is critically overfished due to demand for sushi. A single fish sold for $3.1M in Tokyo.',
        'fun_facts': 'Warm-blooded; can maintain body temperature up to 20°C above surrounding water. Swims continuously — must keep moving to breathe.',
        'native_regions': 'Atlantic, Pacific, and Indian Oceans',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Swordfish',
        'scientific_name': 'Xiphias gladius',
        'family': 'Xiphiidae',
        'habitat': 'Open ocean, deep water during the day, surface waters at night',
        'diet': 'Squid, octopus, bluefish, mackerel, and other fish',
        'average_size': '150–300 cm',
        'max_size': '455 cm',
        'weight_range': '50–650 kg',
        'danger_level': 'Dangerous (long sharp bill)',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Long flattened bill (sword), large eyes, scaleless adult body, prominent dorsal fin, crescent tail',
        'description': 'A highly migratory pelagic predator. Uses its sword to slash through schools of fish. One of the fastest fish in the ocean.',
        'fun_facts': 'Has a special organ to heat its brain and eyes in cold deep water. Juveniles have scales that disappear with age. Can reach speeds of 97 km/h.',
        'native_regions': 'Tropical and temperate oceans worldwide',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Seahorse',
        'scientific_name': 'Hippocampus spp.',
        'family': 'Syngnathidae',
        'habitat': 'Shallow coastal seas, coral reefs, seagrass beds, and mangroves',
        'diet': 'Small crustaceans and zooplankton',
        'average_size': '2–35 cm',
        'max_size': '35 cm',
        'weight_range': '1–150 g',
        'danger_level': 'Safe',
        'edible': 'No (used in traditional medicine)',
        'conservation_status': 'Vulnerable',
        'characteristics': 'Horse-shaped head, upright swimming posture, prehensile tail, bony armour plates, no scales',
        'description': 'The only fish where the male becomes pregnant and gives birth. Monogamous pairs greet each other each morning with a dance.',
        'fun_facts': 'Males carry up to 2,000 young in a brood pouch. Cannot swim fast — they are the slowest fish. Can change colour in milliseconds.',
        'native_regions': 'Tropical and temperate seas worldwide',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Barracuda',
        'scientific_name': 'Sphyraena barracuda',
        'family': 'Sphyraenidae',
        'habitat': 'Tropical and subtropical coastal oceans, reefs, and open sea',
        'diet': 'Fish, squid, and shrimp — ambush predator',
        'average_size': '60–150 cm',
        'max_size': '200 cm',
        'weight_range': '2–50 kg',
        'danger_level': 'Dangerous (fast attack, razor teeth; ciguatera risk if eaten)',
        'edible': 'Caution (risk of ciguatoxin poisoning)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Long torpedo-shaped body, iridescent blue-grey colouring, prominent fang-like teeth, underbite',
        'description': 'An apex reef predator known for its speed and aggressive bite. Can cause ciguatera fish poisoning if consumed from certain regions.',
        'fun_facts': 'Attracted to shiny objects which they mistake for prey. Can swim at over 55 km/h. Young barracudas school in large groups.',
        'native_regions': 'Tropical Atlantic, Pacific, and Indian Oceans',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Coelacanth',
        'scientific_name': 'Latimeria chalumnae',
        'family': 'Latimeriidae',
        'habitat': 'Deep ocean caves at 150–700 m depth',
        'diet': 'Fish, squid, cuttlefish, and eels',
        'average_size': '150–180 cm',
        'max_size': '200 cm',
        'weight_range': '50–100 kg',
        'danger_level': 'Safe',
        'edible': 'No (flesh is foul-tasting and waxy; contains many indigestible compounds)',
        'conservation_status': 'Critically Endangered',
        'characteristics': 'Lobed fins resembling limbs, hollow notochord, blue iridescent scales with white spots, hinged skull',
        'description': 'A living fossil considered extinct for 65 million years until rediscovered in 1938. Its lobed fins are the precursor to tetrapod limbs.',
        'fun_facts': 'One of our closest fish relatives. Has changed little in 400 million years. Gives birth to live young after a 3-year gestation.',
        'native_regions': 'Comoro Islands, South Africa, Indonesia (deep ocean)',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Arapaima',
        'scientific_name': 'Arapaima gigas',
        'family': 'Arapaimidae',
        'habitat': 'Amazon floodplains, lakes, and slow rivers',
        'diet': 'Fish, crustaceans, insects, birds, and small mammals',
        'average_size': '150–200 cm',
        'max_size': '450 cm',
        'weight_range': '20–200 kg',
        'danger_level': 'Mildly Dangerous (large and powerful)',
        'edible': 'Yes',
        'conservation_status': 'Data Deficient (likely threatened)',
        'characteristics': 'Massive elongated body, bony tongue, scales like armour (resistant to piranha bites), dark with red markings',
        'description': 'One of the largest freshwater fish in the world. Must surface every 10–20 minutes to breathe air. Sacred to some Amazonian tribes.',
        'fun_facts': 'Its scales have a complex layered structure that makes them piranha-proof. Tongue is so hard it is used as a grater. Can weigh 200 kg.',
        'native_regions': 'Amazon River basin, South America',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Flying Fish',
        'scientific_name': 'Exocoetidae family',
        'family': 'Exocoetidae',
        'habitat': 'Open tropical and subtropical ocean surface waters',
        'diet': 'Plankton, small crustaceans, and algae',
        'average_size': '17–30 cm',
        'max_size': '45 cm',
        'weight_range': '50–200 g',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Enlarged wing-like pectoral fins, asymmetric tail (lower lobe longer), streamlined silver body',
        'description': 'Can leap out of water and glide through the air up to 400 m using their wing-like pectoral fins to escape predators.',
        'fun_facts': 'Can reach speeds of 70 km/h underwater before launching into the air. Glides up to 6 metres above sea surface. Barbados is called "Land of the Flying Fish."',
        'native_regions': 'Tropical and subtropical oceans worldwide',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Lionfish',
        'scientific_name': 'Pterois volitans',
        'family': 'Scorpaenidae',
        'habitat': 'Coral reefs, rocky crevices, and estuaries in warm seas',
        'diet': 'Small fish, shrimp, crabs, and invertebrates',
        'average_size': '25–38 cm',
        'max_size': '47 cm',
        'weight_range': '0.2–1.2 kg',
        'danger_level': 'Dangerous (venomous dorsal spines — extremely painful)',
        'edible': 'Yes (spines must be removed)',
        'conservation_status': 'Least Concern (invasive in Atlantic)',
        'characteristics': 'Red, white, and brown striped body, long venomous spines, feathery pectoral fins',
        'description': 'A strikingly beautiful reef fish with highly venomous spines. Invasive in the Atlantic, causing massive ecological damage to Caribbean reefs.',
        'fun_facts': 'Venom causes extreme pain, nausea, and temporary paralysis but is rarely fatal to healthy adults. Will eat anything up to half its own size.',
        'native_regions': 'Indo-Pacific; invasive in Atlantic/Caribbean',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Pufferfish',
        'scientific_name': 'Tetraodontiformes',
        'family': 'Tetraodontidae',
        'habitat': 'Coral reefs, estuaries, and sometimes freshwater rivers',
        'diet': 'Molluscs, sea urchins, coral, and algae',
        'average_size': '15–35 cm',
        'max_size': '90 cm',
        'weight_range': '0.1–30 kg',
        'danger_level': 'Dangerous (Tetrodotoxin — can be fatal)',
        'edible': 'Caution (Fugu — only licensed chefs in Japan)',
        'conservation_status': 'Varies by species',
        'characteristics': 'Can inflate to a sphere shape, beak-like fused teeth, spiny skin when inflated',
        'description': 'Contains tetrodotoxin — 1,200 times more toxic than cyanide. Yet "fugu" pufferfish is a delicacy in Japan prepared by licensed chefs.',
        'fun_facts': 'Creates intricate geometric patterns on the seafloor for mating. The inflation reflex is actually a stress response. There is no known antidote to its toxin.',
        'native_regions': 'Tropical and subtropical seas worldwide',
        'water_type': 'Saltwater',
        'in_model': False,
    },
    {
        'name': 'Angelfish',
        'scientific_name': 'Pterophyllum scalare',
        'family': 'Cichlidae',
        'habitat': 'Slow-moving Amazon tributaries with dense vegetation',
        'diet': 'Small invertebrates, insects, zooplankton, and plant matter',
        'average_size': '10–15 cm',
        'max_size': '30 cm (tall)',
        'weight_range': '50–200 g',
        'danger_level': 'Safe',
        'edible': 'No (aquarium fish)',
        'conservation_status': 'Least Concern',
        'characteristics': 'Triangular body with long trailing dorsal/ventral fins, vertical black stripes, disc-shaped when viewed from front',
        'description': 'One of the most popular freshwater aquarium fish globally. In the wild, hides among tall plants using its disc shape for camouflage.',
        'fun_facts': 'Mates for life. Both parents guard eggs and fan them with their fins. Can recognize individual human faces.',
        'native_regions': 'Amazon River basin, South America',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Sturgeon',
        'scientific_name': 'Acipenser spp.',
        'family': 'Acipenseridae',
        'habitat': 'Large rivers, estuaries, and coastal seas in temperate regions',
        'diet': 'Invertebrates, molluscs, crustaceans, and small fish from the bottom',
        'average_size': '100–200 cm',
        'max_size': '600 cm (Beluga)',
        'weight_range': '10–1,500 kg',
        'danger_level': 'Safe',
        'edible': 'Yes (and source of prized caviar)',
        'conservation_status': 'Critically Endangered (most species)',
        'characteristics': 'Five rows of bony scutes instead of scales, toothless mouth with four barbels, heterocercal tail',
        'description': 'Ancient fish whose caviar is among the most expensive foods. Most species are critically endangered from overfishing and dam construction.',
        'fun_facts': 'The Beluga Sturgeon can live 118 years. Can produce caviar only after 20 years. Beluga caviar sells for $35,000/kg.',
        'native_regions': 'North America, Europe, Asia (rivers and seas)',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Betta Fish',
        'scientific_name': 'Betta splendens',
        'family': 'Osphronemidae',
        'habitat': 'Rice paddies, shallow ponds, and slow streams in Southeast Asia',
        'diet': 'Insects, larvae, small invertebrates, and zooplankton',
        'average_size': '5–8 cm',
        'max_size': '9 cm',
        'weight_range': '2–6 g',
        'danger_level': 'Safe (aggressive to own species only)',
        'edible': 'No',
        'conservation_status': 'Vulnerable (wild populations)',
        'characteristics': 'Long flowing finnage in males, brilliant iridescent colours, labyrinth organ for air breathing',
        'description': 'Also known as Siamese Fighting Fish. Males are fiercely territorial and will fight each other. Popular aquarium fish with thousands of colour varieties.',
        'fun_facts': 'Can recognise their own reflection. In Thailand, Betta fish fights are a traditional form of gambling. Each fish has a unique personality.',
        'native_regions': 'Thailand, Cambodia, Laos, Vietnam',
        'water_type': 'Freshwater',
        'in_model': False,
    },
    {
        'name': 'Nile Perch',
        'scientific_name': 'Lates niloticus',
        'family': 'Latidae',
        'habitat': 'Large tropical freshwater lakes and rivers',
        'diet': 'Fish, crustaceans, and insects',
        'average_size': '100–150 cm',
        'max_size': '200 cm',
        'weight_range': '10–200 kg',
        'danger_level': 'Safe',
        'edible': 'Yes',
        'conservation_status': 'Least Concern',
        'characteristics': 'Silvery body, two dorsal fins, large mouth, rounded tail, yellowish eye with black pupil',
        'description': 'Introduced into Lake Victoria in the 1950s where it caused the extinction of over 200 endemic cichlid species — one of history\'s worst ecological disasters.',
        'fun_facts': 'Can weigh over 200 kg. Responsible for the largest mass extinction of vertebrates in recorded history. Yet it is a major food and export fish for East Africa.',
        'native_regions': 'Nile River basin; introduced to Lake Victoria and other African lakes',
        'water_type': 'Freshwater',
        'in_model': False,
    },
]


def seed_if_empty():
    if FishSpecies.query.count() > 0:
        return

    all_fish = MODEL_FISH + EXTRA_FISH
    for data in all_fish:
        fish = FishSpecies(**data)
        db.session.add(fish)

    db.session.commit()
    print(f'Seeded {len(all_fish)} fish species into the database.')
